### ISSUE TITLE
Android Paste button disappears from new link field

### ISSUE THREAD

**Issue by WinstonSmith73** [Dacid99/LinkDroid-for-Linkwarden#9] opened 2024-11-09 15:07 UTC
Tap the plus button, tap New Link, tap-and-hold in the Link field. 

The Android Paste button pops up momentarily and then disappears.

This happens on both my wife's Pixel 6 & my Pixel 6 Pro, running CalyxOS 5.12.0 (Android 14).

**Comment by Dacid99** [comment] 2024-11-09 17:11
Hi thanks for reporting this!

I reproduced it, but with my phone it only occured when the keyboard was visible and it went away after a few tries.

Im not sure theres much I can do to resolve this though, the app simply wraps the webui of Linkwarden and I have no control over its interactions with the android environment. 

Can you check whether this issue also occurs when you use Linkwarden in the browser? If it happens there too then I will not be able to do something about it unfortunately.

Perhaps the best way around this is to just use the share context functionality. Either you share the link using the share interface or you use the long click copy menu where there should be a button for sending to Linkwarden behind the 3 dots.

**Comment by d0dg3r** [comment] 2024-11-09 18:34
Seems to be the webapp. I also happens direct with chrome on the webapp.

**Comment by WinstonSmith73** [comment] 2024-11-10 19:41
I just tested it in Brave, Chromium & FF beta. Doesn't work in the first two so might be a Chrome issue. Works in FF beta.

Reported to LinkWarden project 👍

**Comment by Dacid99** [comment] 2024-11-10 19:54
Alright I hope they can fix it!
Thanks again for reporting this.
Ill close this issue now.

**Closed** 2024-11-10 19:54 UTC
